---
# pegbtech-demo application
version: '3'
services:

  # Pegbtech-demo nginx as web proxy
  pegb-proxy: 
    container_name: pegb-proxy
    image: nginx:1.17-alpine
    ports:
      - "80:80"
      - "443:443"
      - "5443:5443"
    volumes:
      - "$PWD/pegb_web/pegb-proxy/nginx:/etc/nginx/conf.d"
      - "$PWD/pegb_web/pegb-certbot/conf:/etc/letsencrypt"
      - "$PWD/pegb_web/pegb-certbot/www:/var/www/certbot"

    # NGINX will reload its configuration every 6h
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always
    networks:
      - pegbnet

  # Pegbtech-demo certbot for lets encrypt
  pegb-certbot:
    container_name: pegb-certbot
    image: certbot/certbot
    # ports: 
      # 
    volumes:
      - "$PWD/pegb_web/pegb-certbot/conf:/etc/letsencrypt"
      - "$PWD/pegb_web/pegb-certbot/www:/var/www/certbot"

    # Check if your certificate is up for renewal every 12 hours as recommended by Let’s Encrypt.
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: always
    networks:
      - pegbnet

  # Pegbtech-demo the application itself
  pegb-app:
    container_name: pegb-app
    image: spirit986/pegb-app:latest # Pre-built container to speedup the deployment process
    environment: 
      - "HOST=0.0.0.0" # Webpack server will listen on all IPs
    ports:
      - "8080:8080"
      - "3030:3030"
    restart: always
    networks:
      - pegbnet

  # Pegtech-demo api
  pegb-api:
    container_name: pegb-api
    image: pegb-api:latest
    ports:
      - "5000:5000"
    build:
      context: pegb_api
    restart: always
    links:
      - pegb-db
    networks:
      - pegbnet
  
  # Pegtech-demo database
  pegb-db:
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=mongoadmin"
      - "MONGO_INITDB_ROOT_PASSWORD=secret"
    container_name: pegb-db
    image: mongo:4.0-xenial
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/pegb_db/dbdata:/data/db"
      #- "$PWD/pegb-db/mongo.conf:/etc/mongo.conf"
    restart: always
    networks:
      - pegbnet

networks:
  pegbnet:
...
